import re
from typing import Optional, List, Tuple

import requests

from core.base_module import BaseModule, ScanResult, Finding

# (WAF name, detection logic): headers, cookies, body patterns, status codes
WAF_SIGNATURES = [
    ("Cloudflare", {
        "headers": ["cf-ray", "cf-cache-status", "cf-request-id"],
        "cookies": ["__cfduid", "cf_clearance"],
        "body": ["cloudflare", "ray id:", "attention required! | cloudflare"],
        "server": ["cloudflare"],
    }),
    ("AWS WAF / CloudFront", {
        "headers": ["x-amz-cf-id", "x-amz-cf-pop", "x-amzn-requestid"],
        "body": ["request blocked", "aws waf"],
        "server": ["cloudfront"],
    }),
    ("Akamai", {
        "headers": ["x-akamai-request-id", "akamai-grn"],
        "body": ["access denied | akamai", "reference #"],
        "server": ["akamaighost"],
    }),
    ("Imperva / Incapsula", {
        "headers": ["x-iinfo", "x-cdn"],
        "cookies": ["incap_ses", "visid_incap"],
        "body": ["incapsula incident id", "powered by incapsula"],
    }),
    ("F5 BIG-IP ASM", {
        "cookies": ["ts", "tspd_100"],
        "headers": ["x-wa-info", "x-waf-status"],
        "body": ["the requested url was rejected", "f5 networks"],
    }),
    ("ModSecurity", {
        "body": ["mod_security", "modsecurity", "not acceptable!", "406 not acceptable"],
        "headers": ["x-mod-security"],
    }),
    ("Barracuda", {
        "body": ["barracuda networks", "bwaf"],
        "cookies": ["barra_counter_session"],
    }),
    ("Sucuri", {
        "headers": ["x-sucuri-id", "x-sucuri-cache"],
        "body": ["access denied - sucuri website firewall", "sucuri cloudproxy"],
        "server": ["sucuri/cloudproxy"],
    }),
    ("Wordfence", {
        "body": ["generated by wordfence", "your access to this site has been limited by wordfence"],
    }),
    ("Nginx / OpenResty WAF", {
        "server": ["openresty"],
        "body": ["nginx", "openresty"],
    }),
    ("Wallarm", {
        "headers": ["x-wallarm-node"],
    }),
    ("Fastly", {
        "headers": ["x-fastly-request-id", "fastly-restarts"],
        "server": ["varnish"],
    }),
    ("Radware AppWall", {
        "body": ["radware", "appwall"],
        "headers": ["x-sidewinder-transport"],
    }),
    ("Reblaze", {
        "cookies": ["rbzid"],
        "headers": ["x-reblaze-protection"],
    }),
]

# Payloads that commonly trigger WAF blocks
PROBE_PAYLOADS = [
    "/?q=<script>alert(1)</script>",
    "/?q=' OR 1=1--",
    "/?q=../../etc/passwd",
    "/?q=; ls -la",
    "/?q=UNION SELECT NULL--",
]


class Module(BaseModule):
    name = "waf"
    description = "WAF detector — fingerprints Web Application Firewalls and tests bypass potential"
    author = "RedScope"
    version = "1.0.0"

    def run(self, target: str, **kwargs) -> ScanResult:
        result = ScanResult(module=self.name, target=target)
        url = target if target.startswith("http") else f"https://{target}"
        base = url.rstrip("/")

        session = requests.Session()
        session.headers["User-Agent"] = self.config["general"]["user_agent"]
        timeout = self.config["general"]["timeout"]

        self.log.info(f"WAF detection on [bold]{base}[/]")

        # Baseline request
        try:
            baseline = session.get(base, timeout=timeout, verify=False)
        except requests.RequestException as e:
            result.add_error(str(e))
            return result

        # Fingerprint from baseline
        detected = self._fingerprint(baseline)
        if detected:
            waf_name = detected
            self.log.info(f"  [bold yellow]WAF detected:[/] {waf_name}")
            result.data["waf"] = waf_name
            result.add_finding(Finding(
                title=f"WAF Detected: {waf_name}",
                severity="info",
                description=(
                    f"{waf_name} WAF/CDN identified from response headers, cookies, or body. "
                    "This affects the feasibility of direct exploitation attempts."
                ),
                evidence=self._collect_evidence(baseline),
                remediation="Ensure WAF rules are tuned — detection alone does not mean full protection.",
                tags=["waf", "fingerprint"],
            ))
        else:
            self.log.info("  [dim]No WAF detected from baseline response[/]")
            result.data["waf"] = None

        # Probe with attack payloads — see how WAF responds
        block_count = 0
        bypass_count = 0
        probe_results = []

        for path in PROBE_PAYLOADS:
            try:
                resp = session.get(f"{base}{path}", timeout=timeout, verify=False)
                blocked = resp.status_code in (403, 406, 429, 503) or self._fingerprint(resp) is not None
                probe_results.append({
                    "payload": path,
                    "status": resp.status_code,
                    "blocked": blocked,
                })
                if blocked:
                    block_count += 1
                    self.log.info(f"  [yellow]BLOCKED[/] {path} → {resp.status_code}")
                else:
                    bypass_count += 1
                    self.log.info(f"  [red]NOT BLOCKED[/] {path} → {resp.status_code}")
            except requests.RequestException:
                continue

        result.data["probe_results"] = probe_results

        if bypass_count > 0:
            result.add_finding(Finding(
                title=f"WAF Bypass Potential — {bypass_count}/{len(PROBE_PAYLOADS)} Payloads Not Blocked",
                severity="high" if not detected else "medium",
                description=(
                    f"{bypass_count} out of {len(PROBE_PAYLOADS)} attack payloads were not blocked. "
                    + (f"Despite {detected} being detected, some payloads pass through." if detected
                       else "No WAF appears to be blocking malicious requests.")
                ),
                evidence="\n".join(
                    f"[{'BLOCKED' if r['blocked'] else 'PASS'}] {r['payload']} → HTTP {r['status']}"
                    for r in probe_results
                ),
                remediation=(
                    "Review WAF rules to ensure SQLi, XSS, LFI, and command injection payloads are blocked. "
                    "Enable logging and alerting for blocked requests."
                ),
                tags=["waf", "bypass"],
            ))

        if not detected and block_count == 0:
            result.add_finding(Finding(
                title="No WAF Detected — Application Directly Exposed",
                severity="medium",
                description=(
                    "No Web Application Firewall was identified. "
                    "The application appears to be directly exposed without WAF protection, "
                    "making it more vulnerable to automated attacks."
                ),
                remediation="Consider deploying a WAF (Cloudflare, AWS WAF, ModSecurity) in front of the application.",
                tags=["waf", "no-protection"],
            ))

        return result

    def _fingerprint(self, resp: requests.Response) -> Optional[str]:
        headers_lower = {k.lower(): v.lower() for k, v in resp.headers.items()}
        cookies_lower = {c.lower() for c in resp.cookies.keys()}
        body_lower = resp.text.lower()
        server = headers_lower.get("server", "")

        for waf_name, sigs in WAF_SIGNATURES:
            for h in sigs.get("headers", []):
                if h.lower() in headers_lower:
                    return waf_name
            for c in sigs.get("cookies", []):
                if c.lower() in cookies_lower:
                    return waf_name
            for b in sigs.get("body", []):
                if b.lower() in body_lower:
                    return waf_name
            for s in sigs.get("server", []):
                if s.lower() in server:
                    return waf_name
        return None

    def _collect_evidence(self, resp: requests.Response) -> str:
        lines = [f"Status: {resp.status_code}"]
        interesting = ["server", "cf-ray", "x-iinfo", "x-sucuri-id", "x-amz-cf-id",
                       "x-akamai-request-id", "x-fastly-request-id"]
        for h in interesting:
            if h in {k.lower() for k in resp.headers}:
                lines.append(f"{h}: {resp.headers.get(h, '')}")
        if resp.cookies:
            lines.append(f"Cookies: {', '.join(resp.cookies.keys())}")
        return "\n".join(lines)
